version: "3.8"
services:
    dev-db:
        image: mariadb
        container_name: omgdb
        restart: always
        ports:
            - 3306:3306
        environment:
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
    test-db:
        image: mariadb
        container_name: omgdb_test
        restart: always
        ports:
            - 3307:3306
        environment:
            MARIADB_USER: ${TEST_DB_USERNAME}
            MARIADB_PASSWORD: ${TEST_DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
            MARIADB_DATABASE: ${TEST_DB_DATABASE}
